### ISSUE TITLE
Automatically generate description if not provided or too short

### ISSUE THREAD

**Issue by yihui** [rstudio/bookdown.org#3]
Idea: https://yihui.name/en/2017/08/hugo-post-summary/ Extract paragraphs from the book's homepage (using R/xml), and truncate to a certain number of characters.

**Comment by yihui** [comment]
@cderv Perhaps you can help with this one. I'll just let you decide how short is "too short".

**Comment by yihui** [comment]
@cderv Sorry I ruined some of your tidyverse code (in particular, the purrr code) while working on other issues 😊

**Comment by yihui** [comment]
FYI I have finished it (still testing). Thanks anyway!

**Comment by cderv** [comment]
Very interesting to see how you rewrote some code. No worries, I can deal with base R too. I understand why you did this too. I saw some style guide to follow with you no more `<-` but just `=`. 😄 

You go very fast now on this project and it is good. I can't follow the pace during the week because of workload on other subjects. Just morning (like now), end of day or week end. I'll be there to help you when needed but for now I think you are way more efficient by yourself! 

Very nice improvements, the website looks very good !

**Comment by yihui** [comment]
I'm working full-time on it, so yeah, I can go very fast.

I'm totally fine with `<-` if the code is written and maintained by a `<-` person. If I'm going to touch the code and maintain it by myself, I'll switch to `=`.
