### ISSUE TITLE
Automate fetching books and publishing the site

### ISSUE THREAD

**Issue by yihui** [rstudio/bookdown.org#63]
Currently I ran `R/create-md.R` manually locally to fetch books from bookdown.org and other external sources. Then I inspect the diffs manually, and commit the desired changes. Finally I re-publish the site with `R/publish.R` manually.

I wish to use GHA to automate both steps. For example, we could use GHA to fetch the books and create a PR each week. Note that this needs caching book data to `R/_book_meta.rds` to avoid fetching books that haven't been updated since the previous week. Without caching, it will be very time-consuming. I have a local copy of `_book_meta.rds` here: [_book_meta.rds.zip](https://github.com/rstudio/bookdown.org/files/6079242/_book_meta.rds.zip)

**Comment by cderv** [comment]
- [ ] Auto generate md and create a PR
- [ ] Auto build the new website and publish

**Comment by cderv** [comment]
@yihui which version of hugo should we use for this website ?

**Comment by cderv** [comment]
Book will now be built and deploy on each commit to master. 
That means when merging the auto PR. 

Did you have another trigger in mind or is this ok ? 

For now, it installs the latest hugo version. Should we pin the version to install ?

**Comment by cderv** [comment]
About the `staging.txt` process, What do you do manually ? 

It seems nothing - Do I have it correctly ? 

1. When someone makes a PR with staging.txt ad .md file will be created 
2. When we merge it gets included in the file to be built
3. This file will never be removed or modified because the URL will never be fetched for information again. I say that because it is not (1) part of bookdown.org (2) part of external.txt 

Do I get the third point right ? 

Looking into that to remove the travis part.

**Comment by cderv** [comment]
Thanks, I'll see how I can automate this so that we have no manual step at all 

* Someone PR adding a url in staging
* We get a preview of the md file to review
* We decide to include and then got the new site built + link moved to `external.txt`

**Comment by cderv** [comment]
I added a workflow now to build the md file for a new book added on staging. 

- The user will open a PR with the `staging.txt` file
- The workflow will trigger on PR, only those which contains a change to `staging.txt`. It will: 
   - Run `create-md.R` that knows how to handle `staging.txt`: It will only process the url in the staging area, and only modify this md files
   - When it is done, the workflow will add the content of `staging.txt` to `external.txt`, and remove any content in `staging.txt`
   - It will the commit and push the change to the PR. 
- We then need to review this 

You can see an example in #76. It contains some tests commit but the idea is there and the last changes you see if what we should have after someone open a PR. 

The change compare to your workflow is that the `.md` file is created from the one the url in staging, and not by processing everything again after merging the url into `external`. 

If I got it wrong I may need to change the order in which things are done. I've done it this way because the trigger is easier: do everything when someone open a PR. I can do more complicated to build the website only after the changes are merged in master or similar.

Is it ok like that ? 

I merged the mentioned PR above but I'll take into account your feedback if any. 

If this is ok - you can close this issue! 

Thanks

**Comment by yihui** [comment]
That's perfect! Thanks a lot!
